// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ChatHub.Models
{
    public partial class Message
    {
        [Key]
        public int message_id { get; set; }
        [Required]
        [StringLength(50)]
        public string message_text { get; set; }
        [Required]
        [StringLength(50)]
        public string user_name { get; set; }
        [Required]
        [StringLength(50)]
        public string message_date { get; set; }
    }
}